name: CI

on:
  schedule:
    - cron: '10 2 * * *' # 毎月1日に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: npm ci
      - name: entrypoint
        env:
          WORK_ENV: Github Actions
          TRAQ_ACCESS_TOKEN: ${{secrets.TRAQ_ACCESS_TOKEN}}
          TRAQ_POST_CHANNEL: ${{secrets.TRAQ_POST_CHANNEL}}
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        run: node scripts/index.js
